### ISSUE TITLE
현재 슬랙 커뮤니티 버전의 문제점(메세지 저장 제한)을 해결할 방안 검토

### ISSUE THREAD

**Issue by BoomLEE** [kodevops/guideline#1]
TODO
・현재 슬랙의 문제점(메세지 저장 제한)을 해결할 방안 검토
  - 문제점 : 메세지 저장한도로 인한 과거 메세지 사라짐
  - 검토 ? : 1. 슬랙 외 다른 대체서비스 도입 ( 기존유저 이동 및 사용편리성)
                  2. 설치형 슬랙과 같은 서비스를 도입 ( 운용부담이 늘어나게됨)
                  3. 슬랙 유료 플랜 ( 돈이 많이듬 1유저 한달 880엔정도)
                  4. 슬랙 비영리 단체 플랜을 이용 ( 비영리단체/법인이 되어야함,, 관리코스트?)
                  등등
https://ja.wikipedia.org/wiki/非営利団体

**Comment by BoomLEE** [comment]
관련링크 http://www.ngo21.net/ngo21admin/adaction/down/07%B9%CE%BA%B4%B7%CE.pdf

**Comment by richellin** [comment]
좋은 대안책이 없으므로 현 상태를 유지하도록 하겠습니다.
