### ISSUE TITLE
[블로그] 28차 고군분투기 작성

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#10]
[26차 고군분투기](https://kodeveloper.com/%EA%B3%A0%EA%B5%B0%EB%B6%84%ED%88%AC%EA%B8%B0/2018/11/18/struggle-26/)를 참고하여 28차 고군분투기 작성하기

- heo jonggu: [Mysql innodb architecture](
https://docs.google.com/presentation/d/1EErikAbk8IhU7qhR3wwyGVDW2qlkZUqEXVilEebIOxY/edit?usp=sharing)
- ju.inho: [Mysql 가용성](https://drive.google.com/open?id=1NRSIuCg7wBW4LMDDa86ClysC8cZCudt7)

**Comment by minsoo-jun** [comment]
![28meetup](https://user-images.githubusercontent.com/2956728/52617726-22a06600-2ee0-11e9-88a8-1e400630937c.jpg
)
![28heo](https://user-images.githubusercontent.com/2956728/52617893-9f334480-2ee0-11e9-9a0a-5bcfc93426b7.jpg
)
![28ju](https://user-images.githubusercontent.com/2956728/52617983-df92c280-2ee0-11e9-973a-5e4b091c5409.jpg
)
![281](https://user-images.githubusercontent.com/2956728/52618105-37c9c480-2ee1-11e9-94f3-d21e1ca8973c.jpg)

![282](https://user-images.githubusercontent.com/2956728/52618151-5d56ce00-2ee1-11e9-869c-7ba3e41de68a.jpg)

![283](https://user-images.githubusercontent.com/2956728/52618187-73648e80-2ee1-11e9-9f53-3d62b3b7deea.jpg)
