### ISSUE TITLE
앞으로 스태프 새로운 운영방식 및 고군분투기 새 포맷 제안.

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#13]
긴급: GW가 있어서 32차 고군분투기 장소 사람 섭외를 빨리 진행 해야됨.
기한: 2019/04/25일

## 문제점 1

슬랙에서 실시간으로 의견을 주고받는건 좋지만, 시간이 지나버리거나, 다른 채팅 내용으로 인해 묻혀지면 
찾기도 어렵고, 누가 봤고 대응을 했는지가 알기가 어려움.

### 개선안

1. 모든 이슈는 guildline의 이슈에 등록
2. 이슈 관리는 trello로 처럼 쓸수 있도록 Zenhub와 연동해서 이슈를 관리
3. 모든 스태프는 확인을 한 이슈에 대해서는 반드시 `댓글`을 등록
※ 확인을 했는지 않했는지를 알기위해서 반응을 해주세요.
4. 이슈 관리자는 2달에 한번씩 로테이션
[관리표](https://docs.google.com/spreadsheets/d/1REFbMAbKVsbe_9MFezPaKiOmuZnhPaGem68HRQ_jZSg/edit#gid=894025752)를 참고 해주세요.
※ 자신의 차례가 끝나면 다음 스태프에게 알리기
※ 부득이한 사정으로 인해 운영이 불가능 할경우 다른 스태프와 상담을 해서 순서를 바꾸기
4. 모든 이슈에 대해서 기한(+@ 긴급) 설정 하기
5. 이슈를 등록하면 반드시 #staff 채널 또는 이슈 관리자에게 알리기
6. 의견(이슈)이 대립할시에는 다수결 원칙으로 진행
7. 의견(이슈)이 대립할시 정해진 기한내에 답변이 없는 운영자의 경우에는 기권으로 처리
8. [미션 / 비젼](https://kodeveloper.com/about/)을 기준으로 움직이기(초심 잃지 않기)

## 문제점 2

31차 고군분투기에서 나온 의견을 종합해서 새로운 운영 방식을 제안

### 개선안

- 진행 및 준비
   진행 및 준비는 2달에 한번씩 로테이션
   [관리표](https://docs.google.com/spreadsheets/d/1REFbMAbKVsbe_9MFezPaKiOmuZnhPaGem68HRQ_jZSg/edit#gid=894025752)를 참고 해주세요.
    ※ 자신의 차례가 끝나면 다음 스태프에게 알리기
    ※ 부득이한 사정으로 인해 운영이 불가능 할경우 다른 스태프와 상담을 해서 순서를 바꾸기

- 발표자  모집
    1.기본적으로 발표자 모집은 아래의 상시 아래의 공고로 진행하며, 신청자는 아래의 공고란에 댓글(신청)로 신청
    - [정식 발표자 모집 - draft](https://github.com/kodevops/struggle/issues/5)
    - [LT 발표자 모집 - draft](https://github.com/kodevops/struggle/issues/4)

    2.+@로 운영진이 기회가 있으면 특별 게스트를 초청.

- 장소
    - 장소는 기본적으로`코트라`를 섭외
    - +@로 다른장소가 섭외 가능하면 섭외

- 일정 및 시간
   - 현행 유지

**Comment by kimjoin2** [comment]
LT 발표자 모집 - 신청 방법 - 예) 에서 좀 더 가볍게 접근할 수 있도록
순수 개발이 아닌 다른 주제의 예시도 있었으면 좋겠습니다.
이전의 고군분투기 발표에서 예시를 가져온다면
비트코인, 카메라, 라인페이, 부양가족 절세, etc...

그 외엔 좋은 것 같습니다!

**Comment by richellin** [comment]
@kimjoin2 

아래의 예시와 같이 예제를 만들어서 제안 해주실래요? (바로 써먹게 ㅎㅎ)
```
예)
- 성함(slack): 이상준(@sangjun)
- 발표 희망 일정: 5월 10~20일,  6월 10~20일,  7월 10~20일
- 주제: Firebase Realtime Database를 이용해서 간단한 채팅 시스템 만들기(With PHP)
- 간단한 내용: Custom token를 이용해서 어떻게 세큐리티를 담보하며, 실시간으로 화면에 채팅이 적용되게 하는지 설명
※ 현장에서 Firebase Realtime Database 자체에 대해서 잘모르면 Realtime Database를 쓰면 이런거 가능함 ㅇㅋ?로 마무리)
- 자료 URL: xxxxxx
```

**Comment by kimjoin2** [comment]
@richellin 

간단히 예시를 만들어보았습니다.

```
예)
- 성함(slack): 김범녕(@김범녕)
- 발표 희망 일정: 7월 혹은 8월
- 주제: 클라우드 마이닝 맛보기
- 간단한 내용: 마이닝의 개요부터 클라우드 마이닝으로 불로소득을 얻기까지 
- 자료 URL: xxxxxx
```
```
예)
- 성함(slack): 김범녕(@김범녕)
- 발표 희망 일정: 7월 혹은 8월
- 주제: 세금 돌려받기!
- 간단한 내용: 부양가족 공제와 후루사토 납세 
- 자료 URL: xxxxxx
```

**Comment by richellin** [comment]
@kimjoin2
굿! 좋습니다 :)
적용 했습니다.

**Comment by BoomLEE** [comment]
우선 제안해주셔서 감사합니다. 
기본적으로 제안해주신 의견에 대해서 좋다고 생각합니다! 
(현재 이슈에 대한 기한이 당장 오늘이기 때문에 일단 내주신 안으로 진행하는게 좋을듯합니다.)

**Comment by buzzricksons** [comment]
저도 동의합니다. 개인적인 의견 하나는 시작시간을 8시 시작 이외에 7시 시작도 한번 진행해 보는건 어떨까 싶습니다.

**Comment by richellin** [comment]
@BoomLEE 
@buzzricksons 

확인 감사드립니다.
시작 시간을 조율하는거 좋습니다. 
고군분투기를 리드할 담당자가 재량것 일정을 결정하는 형식은 어떻세요?

**Comment by BoomLEE** [comment]
>고군분투기를 리드할 담당자가 재량것 일정을 결정하는 형식은 어떻세요?

좋습니다!

**Comment by PowerPalace** [comment]
답변이 늦어져서 죄송합니다. 
찬성입니다.

카메라 테마가 다시 돌아온다면 가볍게 LT한번 참가 해보고싶네요.

**Comment by minsoo-jun** [comment]
Note :)

**Comment by richellin** [comment]
새로운 운영방식으로 스타트를 하였으므로, 현 이슈는 닫겠습니다.
