### ISSUE TITLE
슬랙내 질문&답변을 폐지 하고 싶습니다!

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#14]
### 배경
주옥같은 답변들이 없어지는게 너무 가슴아픔.ㅠㅠ

### 제안
1. 질문자는 Github 특정 레포지토리(Q&A)를 통해서 질문을 함.(이슈 등록)
2. 운영자는 특정 질문을보고 “태그“화 (필수 아님)
3. 질문이 등록되면 슬랙 + 페이스북에 질문이 왔다고 알림.
4. 답변자는 채널을 통해서 질문을 확인후 답변
5. 질문자는 답변이 완료되면 이슈 닫음(또는 운영자가 닫음)

같은 느낌?이 어떨까 하는데 다들 어떻게 생각하세요?

### 정리
Option1. 질의응답 채널 폐지, 깃허브 이슈로 질의 응답하기.
Option2. 질의응답 채널 유지, 현재 운영안 그대로.
Option3. 질의응답 채널 유지, 스탭이 글 정리 후 페이스북 업로드.
Option4. 질의응답 채널 유지, 스탭이 글 정리 후 페이스북 업로드+(Data Backup - Google spreadsheet + GAS)
Option5. 질의응답 채널 유지, 슬랙의 포스트 또는 쓰레드를 이용
Option6. 질의응답 채널 유지, 스탭이 글 정리 후 깃허브에 정리하기.(wiki?)

다음주 오전 9시까지 추가 의견이 없으시다면 현재까지 나온 옵션을 베이스로 진행 방향을 정하면 될 것 같습니다.

### 예문
```
Q, 중국 출장시 비자준비 진행 시의 경험과 중국출장 팁을 공유해주세요.
: 컨퍼런스 발표로 중국에 출장을 가게 되었습니다. 중국 출장은 상용 비자가 필수로 알고 있습니다. 
아마도 비자 신청을 회사 여행사에서 대행해 줄 듯합니다.
진행하는 방법(여행사 대행 또는 개인이 준비)에 따라 다르겠지만 경험이 있으시다면 공유해주세요!

A1. 경험 공유 (상용비자)
1. 신청 후 발급까지 보통 일주일이고, 긴급? 으로 신청하면 2-3일 정도만에 나옵니다.
2. 초청장 필요합니다. 회사 여행사 있으니 필요한 서류는 다 알려줄거에요.
3. 한국인 비자 발급이 제한된다는 기사가 있으니 참고를.
https://news.naver.com/main/read.nhn?mode=LSD&mid=sec&sid1=001&oid=277&aid=0004478454 

A2. 경험 공유 (상용비자)
중국비자는 개인이 처리하는건 없을거에요
중국 영사관 앞에 있는 여행사 통해서 해야되는 식일거에요

A3. 경험공유 (관광비자의 경우)
[사전 준비]
1. 호텔 예약
2. 비행기 예약
3. 호텔, 비행기 예약한걸 프린터
4. 증명사진(주의: 배경은 하얀색!): 당일 비자 신청하러 가서 사진 찍으셔도 상관없음.(800엔)
5. 여권 + 사본: 현장에 복사기 있음.
6. 재류카드 + 사본
7. 비자 신청서

[비자 신청서]
 온라인으로 신청서를 작성한뒤 프린터(꽤 김...)
https://www.visaforchina.org/TYO_EN/
 高速リンク→審証
 tip: 작성하면서 중간에 작성한게 날라 가더라도 충격을 받지 않기위해서, 잦은(?) 일시 저장을 추천..

8. 비자 신청하러 가기.
月曜日から金曜日まで（祝日除外）
申請受付時間：午前９時から午後３時まで

業務時間と所在地
東京ビザ申請センター
東京都港区虎ノ門4-1-17神谷町プライムプレイス８階
https://www.visaforchina.org/TYO_JP/aboutus/281029.shtml

9. 신청완료.
 주의: 여권 가져감.

10. 신청한뒤에 받으러 오라는 날짜에 돈들고 찾으러 가시면됨.
돈 9800엔

月曜日から金曜日まで（祝日除外）
申請受付時間：午前９時から午後３時まで

業務時間と所在地
東京ビザ申請センター
東京都港区虎ノ門4-1-17神谷町プライムプレイス８階
https://www.visaforchina.org/TYO_JP/aboutus/281029.shtml

Tips
Q) 넷플릭스도 접속 안되는 나라에 가면 정말 출장이 지루할듯하네요..ㅠㅠ
A)amazon 에 홍콩 유심 팝니다. 그거 사가시면 되요
vpn 차단 정책도 시행중이니까, 저라면 저 홍콩 USIM 을 추천합니다. 빠르고 차단도 안되고 좋아요.-
용량이 조금 애매한데, 모자라면 충전해서 쓰면 딱히 불편한건 없어요-
```
> 작성하고 정리한 글에 대한 펙트 체크를 하던중,,
중국출장에 대해 잘 정리된 글이 있었습니다.
https://platum.kr/archives/96750
만약 스텝이 작성을 한다고 하더라도 모든 질의응답이 아닌 이건 남기는게 좋을 것같다는 리퀘스트 베이스로 스텝이 정리하는 방향도 나쁘지 않다고 생각하게 되었습니다

**Comment by richellin** [comment]
@BoomLEE 
이슈대장님 이거 어떻게 하기로 결정 난거 였죠.. = _ =?

**Comment by kimjoin2** [comment]
Option3. 질의응답 채널 유지, 스탭이 글 정리 후 페이스북 업로드.
위의 안이 최다득표 했었습니다
슬랙 글은 오래되어서 없어진 것 같습니다.

**Comment by richellin** [comment]
스탭이 글 정리 후 페이스북 업로드 하는건 현실적이지 않기때문에, 현상황을 그대로 유지.
