### ISSUE TITLE
블로그 내 원본이미지 크기 큰걸로 대체

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#16]
1 ~ 32차 고군분투기까지 사진 사이즈가 작으므로,
가로 600이상인 이미지로 대체하기.

예)
![image](https://user-images.githubusercontent.com/9281881/60632861-ea73d280-9e42-11e9-99d2-ddb5f787815e.png)

사진은 [페이스북 앨범](https://www.facebook.com/groups/kodeveloper/photos/?filter=albums)에서 다운로드 한뒤에 교체!

이미지 교체하는 장소는 아래와 같습니다.
[https://github.com/kodevops/blog/tree/master/img/struggle](https://github.com/kodevops/blog/tree/master/img/struggle)

**Comment by richellin** [comment]
![image](https://user-images.githubusercontent.com/9281881/60632861-ea73d280-9e42-11e9-99d2-ddb5f787815e.png)

**Comment by richellin** [comment]
대장님 작업 하실때 임마도 같이 버젼업 해주시면 아리가또!

![image](https://user-images.githubusercontent.com/9281881/63404185-2d066400-c41d-11e9-8741-b08721d93af8.png)

**Comment by minsoo-jun** [comment]
노가다다!

**Comment by minsoo-jun** [comment]
특기죠!

**Comment by kimjoin2** [comment]
노가다 시작하겠습니다. ㅋㅋ

**Comment by kimjoin2** [comment]
1 ~ 32차 고군분투기까지 가로 600미만인 이미지를 큰 이미지로 대체하기까지 배포 완료
"nokogiri" 버전업 관련에서는 "Gemfile.lock" 파일 안에 4곳에서 등장하는대 어떻게 해야할지 잘 모르겠어서 손을 못댔습니다

**Comment by richellin** [comment]
이미지 수정해주셔서 감사드립니다.
취약점 관련해서는 수정 완료 했습니다.
