### ISSUE TITLE
[가이드라인] 블로그 가이드라인 작성

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#19]
1. 작성방법 + 운영
2. 저장소(https://github.com/kodevops/guideline/wiki)

**Comment by richellin** [comment]
검토 필요.

**Comment by richellin** [comment]
검토 필요

**Comment by richellin** [comment]
> draft 만들어놓겠습니다
From DAEBUM LEE

**Comment by kimjoin2** [comment]
https://github.com/kodevops/blog/blob/master/docs/README.md
기존 내용에서 어떤점을 개선해야한다고 생각하고 계신지 알려주시면 감사할 것 같습니닷!

**Comment by richellin** [comment]
@BoomLEE 
최근에 작업하신 대범님 개선 사항에 대해서 정리를 해주시면 감사드립니다.

**Comment by richellin** [comment]
운영진분들이 특별히 문제없이 블로그 작성을 하고 있기때문에
해당 내용은 클로즈 하도록 하겠습니다.
