### ISSUE TITLE
고군분투기 입퇴실시 체크리스트 정리

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#20]

**Comment by richellin** [comment]
체크리스트

    - 입장
        - 주변 기기 (원)위치 및 갯수 확인
            - 마이크
            - 스피커
            - 리모콘
            - 어댑터
            - 의자
            - 책상
            - 열쇠
            - 카드
            - 스크린
        - 주변 시설 위치 확인
            - 화장실
            - 흡연실
            - 비상 탈출구
        - 주의 사항
            - 회의실 입퇴실시 확인 해야 주의사항 묻기.
                - 이벤트가 시작된두 참가자가 회의실까지 오기 위한 루트 또는 방법.
                - 이벤트가 끝나기전 참가자가 집을 가기 위한 루트 또는 방법.
        - 매너
            - 회의실을 빌려주신 관계자에게 "감사"의 인사말을 건낼것.
            
 
    - 퇴장
        - 주변 기기 위치 및 갯수 확인 및 원상 복구
            - 쓰레기 정리
            - 책상, 의자 원상 복구
            - 참가자가 두고간 물품이 없는지 확인
            - 전기(불) 확인
            - 스크린 원상 복구
            - 남아 있는 참가자가 없는지 확인
            - 참가자가 대여해준 주변 기기가 참가자 품으로 완벽하게 돌아 갔는지 확인
        - 매너
            - 회의실을 나갈때는 빌려주신 관계자와 이상이 없는지 운영진은 최종 확인후 "함께" 퇴장 할것.
            - 빌려주신 관계자가 모든 정리가 끝날때 까지 운영진은 1층에서 기다리고 "감사"의 인사말을 건내고 같이 집에 갈것.

    - 예외 상황
        - 운영진 참가자가 적을땐, 미리 주변 참가자들 몇분을 섭외 할것.
            - 다같이 합시다~~ 라고 하는거 보다 몇명을 찝어서 도움을 받는게 훨씬 효과적.
        - 발표자 또는 장소가 부득이하게 당일날 캔슬 날수도 있으니, 이벤트 당일은 즉각 조치를 할수 있도록 안테나를 새울것.
            - 시간이 부족할시에는 모든 결정은 고군분투기 진행자에게 위임합니다.

**Comment by kimjoin2** [comment]
이정도면 충분한 것 같습니다만
다른분들 의견있으시면 주시면 감사할 것 같습니다.

**Comment by richellin** [comment]
https://github.com/kodevops/guideline/blob/master/checklist-conference-room.md
추가 완료.
