### ISSUE TITLE
블로그 발표자 주제 및 자료 추가(33차 ~ 35차)

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#21]
추후 수정이 필요한 리스트
- 33차 고군분투기
    - 발표자 이름은 수정했으나, 발표 자료에도 주제가 없고, 안내 문구에도 주제가 없었기 때문에 주제는 누락된채로 수정완료. 주제 아시는분이 계시면 추가로 수정좀 부탁 드립니다.
- 34차 고군분투기
	- @mj.park : AWS 환경 구축 및 운영과 보안 - 1편 AWS환경 구축
- 35차 고군분투기
	- @Minseong Na : IDaaS를 포함한 XaaS

**Comment by richellin** [comment]
@BoomLEE 
@minsoo-jun 
@kimjoin2 
@buzzricksons 
확인을 부탁드려도 괜찮을까요~?

**Comment by kimjoin2** [comment]
확인이 필요한 내용
33차 : 각 발표의 주제
34차 : 명진님 발표 자료
35차 : 민성님 발표 자료
가 맞을까요?

**Comment by richellin** [comment]
@kimjoin2 
확인이 늦엇습니다. 맞습니다~!

**Comment by richellin** [comment]
모든 자료는 비공개로 수정하기.

**Comment by richellin** [comment]
추가 대응
- 고군분투기 실시 날짜에 맞춰서 컨텐츠 파일 수정
- 모든 고군부투기 컨텐츠에 장소 주소 추가
- 1주년 기념에 티저 영상, 본영상 추가
- 9차 고군분투기 @yaksaa21: Reactive & java 의 링크가 404라서 비공개로 수정
- 발표 자료 링크가 있는 녀석들은 썸네일 같은 느낌으로 이미지 추가
- 발표 자료중에 임베디드 형식으로 표현이 가능 하는 얘들은 전부 슬라이드가 보이도록 수정

**Comment by richellin** [comment]
https://github.com/kodevops/blog/pull/36
대응 완료.
