### ISSUE TITLE
리모트 고군분투기 가이드 작성

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#26]
- 유용한 플러그인 안내
- 진행중 자주 묻는 질문 및 대응법 작성.

**Comment by kimjoin2** [comment]
- 유용한 플러그인 안내
어떤 플러그인을 말씀하시는건가요? (google meet? sli.do? 프레젠테이션을 돕는 서비스?)
- 진행중 자주 묻는 질문 및 대응법 작성
고군분투기 진행 중 발표자가 진행자에게 묻는 질문이라 생각해도 될까요?

**Comment by BoomLEE** [comment]
이 이슈는 범녕님이 벌써 대응해주셨던 온라인 고군분투기 [발표](https://docs.google.com/presentation/d/1umfseJqX_lzI7b6ReDydNbzw5Co-iOFYOJgGzHbBfFA/edit)/[참가](https://docs.google.com/presentation/d/1o3fFEnqLxV6cHnUFxPGLyoRXu5EwTbB7FPMOf4_h_EU/edit#slide=id.p) 안내 매뉴얼로 대응이 완료 되었습니다 (__
