### ISSUE TITLE
[블로그] 42차 고군분투기 

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#34]
- 페이스북 앨범: https://www.facebook.com/media/set/?set=oa.694700014459593&type=3
- 모집 공고: https://forms.gle/Pbg71Y3aDG8BUcV97
- 안내 자료: https://docs.google.com/presentation/d/1ZHCw8k5uLYB_dL4uSJ0LqUWzvXqWAP1-sGbKlIlSwRs/edit?usp=sharing

**Comment by richellin** [comment]
지은님 자료. https://drive.google.com/drive/folders/1BL5nggQqQZSH9t93FAa3VasT7rWQwDgA

**Comment by buzzricksons** [comment]
## TODO

### 발표자료
- 야마다 탓페이님
- 정예한님
- 이대범님
- 김범녕님

### 유튜브 영상링크

**Comment by buzzricksons** [comment]
완료
