### ISSUE TITLE
[블로그] 37차 고군분투기 블로그에 발표자 자료 게시하기

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#36]
숙제 안낸 사람.
- 김범녕(@김범녕) : GAS(Google Apps Script)+Firebase활용하기
- 전민수(@manggu) : SRE(Site Reliability Engineering)

**Comment by kimjoin2** [comment]
링크 : https://docs.google.com/presentation/d/1m28GpV195OtZrHvHO3YmEMTdeXwKTK9J6nuZlkjwXk8/edit?usp=sharing
입니다. 감사합니다 _ _)

**Comment by richellin** [comment]
민수님 비공개

**Comment by richellin** [comment]
https://github.com/kodevops/blog/pull/50
