### ISSUE TITLE
45차 블로그 작성

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#42]
- 안내 자료: https://docs.google.com/presentation/d/1ITmJmlK20VerN05TjKHOQmznxxN9Cw9tyFjPZWGg7PI/edit?usp=sharing
- 재택 근무 지름기 - 요다님: https://docs.google.com/presentation/d/1ufliV8pUP1z-DNtUkw7m-xuVw3nmMS_UOiGcchR-J0Q/edit?usp=sharing
- 페이스북 앨범 - https://www.facebook.com/media/set/?set=oa.902223340539899
- 한국 SW개발자 인생살이(커리어)에 대한 연구 - 노성철님:  https://drive.google.com/file/d/1k3mk8wxM7jOl0MF5EcAx0eTNGw7KxFqb/view?usp=sharing

- 가족 이민과 새로운 커리어의 시작 - 일주님: https://drive.google.com/file/d/1emj6_XYM1h4jvxt4ga4u_Vjo7IcThQBb/view?usp=sharing
- 사룡님 - TODO

**Comment by kimjoin2** [comment]
PR : https://github.com/kodevops/blog/pull/52

**Comment by kimjoin2** [comment]
45 -> y2020end, 46 -> 45
PR : https://github.com/kodevops/blog/pull/53
