### ISSUE TITLE
29차 고군분투기

### ISSUE THREAD

**Issue by BoomLEE** [kodevops/guideline#6]
일시: 2월14일(목) 20:00 ~ 22:00 

- [x] 주제 정하기
- [x] 장소 섭외하기
- [x] 발표자 섭외하기

**Comment by BoomLEE** [comment]
장소 섭외하기 >> 수한님의 도움으로 섭외되었습니다.
( 2월14일 19시30분부터 22시30분까지 고군분투기 세미나 )

**Comment by richellin** [comment]
주제 정하기 >> 코딩 테스트
발표자 섭외하기 >> @Soohan Ahn, @Sa-ryong Kang

**Comment by richellin** [comment]
주제 정하기 >> 코딩 테스트
장소 섭외하기 >> FreakOut(@SooHan Ahn)
발표자 섭외하기 >> @SooHan Ahn, @Sa-ryong Kang
