### ISSUE TITLE
1차 고군분투기 ~ 25차 고군분투기 내용 수정하기.

### ISSUE THREAD

**Issue by richellin** [kodevops/guideline#8]
[26차 고군분투기](https://kodeveloper.com/%EA%B3%A0%EA%B5%B0%EB%B6%84%ED%88%AC%EA%B8%B0/2018/11/18/struggle-26/)를 참고하여, 포맷에 맞춰서 내용 수정하기.

- [ ●] 1차 고군분투기
- [ ●] 2차 고군분투기
- [ ●] 3차 고군분투기
- [ ●] 4차 고군분투기
- [● ] 5차 고군분투기
- [ ●] 6차 고군분투기
- [ ●] 7차 고군분투기
- [ ●] 8차 고군분투기
- [ ●] 9차 고군분투기
- [ ●] 10차 고군분투기
- [ ●] 11차 고군분투기
- [ ●] 12차 고군분투기
- [ ●] 13차 고군분투기
- [ ●] 14차 고군분투기
- [ ●] 15차 고군분투기
- [ ●] 16차 고군분투기
- [ ●] 17차 고군분투기
- [● ] 18차 고군분투기
- [●] 19차 고군분투기
- [●] 20차 고군분투기
- [●] 21차 고군분투기
- [● ] 22차 고군분투기
- [●] 23차 고군분투기
- [● ] 24차 고군분투기(공유할 자료가 없뜸 받아서 올려야됨)
- [● ] 25차 고군분투기(공유할 자료가 없뜸 받아서 올려야됨)

**Comment by minsoo-jun** [comment]
for 25
![25lee](https://user-images.githubusercontent.com/2956728/52677143-0fd57200-2f70-11e9-8b42-b598f715af98.jpg)


![25kang](https://user-images.githubusercontent.com/2956728/52676689-57f39500-2f6e-11e9-9722-4eb7c7437001.jpg)

![25full](https://user-images.githubusercontent.com/2956728/52676913-2fb86600-2f6f-11e9-87c5-bd6fb743926d.jpg)

**Comment by minsoo-jun** [comment]
for 24
![24kim](https://user-images.githubusercontent.com/2956728/52678977-d5bb9e80-2f76-11e9-80dc-e672d8f60031.jpg)

![24full](https://user-images.githubusercontent.com/2956728/52679102-537faa00-2f77-11e9-9470-819482724d78.jpg)

**Comment by minsoo-jun** [comment]
for 23

![23jun](https://user-images.githubusercontent.com/2956728/52686244-2be90b80-2f90-11e9-8322-f844fe437d5e.jpg)

![23gdpr](https://user-images.githubusercontent.com/2956728/52686284-533fd880-2f90-11e9-8a43-9bd3ff645352.jpg)

![23full](https://user-images.githubusercontent.com/2956728/52686446-188a7000-2f91-11e9-970f-c7be9260dd9f.jpg)

**Comment by minsoo-jun** [comment]
for 22

![22u02](https://user-images.githubusercontent.com/2956728/52689483-ac623900-2f9d-11e9-8e17-77a2a2bc73de.jpg)

![2219](https://user-images.githubusercontent.com/2956728/52689547-e8959980-2f9d-11e9-8930-01aedb182269.jpg)

![22full](https://user-images.githubusercontent.com/2956728/52689641-2692bd80-2f9e-11e9-8ec1-f9c9292263b7.jpg)

**Comment by minsoo-jun** [comment]
for 21
![21park](https://user-images.githubusercontent.com/2956728/52689882-22b36b00-2f9f-11e9-9bc2-c4dac82e5867.jpg)

![21ahn](https://user-images.githubusercontent.com/2956728/52689935-4d9dbf00-2f9f-11e9-81f0-6d0af0fc4d3a.jpg)

![21moon](https://user-images.githubusercontent.com/2956728/52689966-745bf580-2f9f-11e9-934d-0ee922166e35.jpg)

![21full](https://user-images.githubusercontent.com/2956728/52690083-db79aa00-2f9f-11e9-9bce-1822ae8e2ee6.jpg)

**Comment by minsoo-jun** [comment]
for 20
![20monn](https://user-images.githubusercontent.com/2956728/52690901-7f645500-2fa2-11e9-9f7c-ad934e7512e0.jpg)

![20biwol](https://user-images.githubusercontent.com/2956728/52690965-b3d81100-2fa2-11e9-80ae-a09b8d6ddfc6.jpg)

![20full](https://user-images.githubusercontent.com/2956728/52691049-00235100-2fa3-11e9-965e-ba6e09da02a0.jpg)

**Comment by minsoo-jun** [comment]
for 19
![19simon](https://user-images.githubusercontent.com/2956728/52692635-ca349b80-2fa7-11e9-8052-164766348b73.jpg)

![19yoda](https://user-images.githubusercontent.com/2956728/52692739-14b61800-2fa8-11e9-9ce9-30b1dd16257f.jpg)

![19doil](https://user-images.githubusercontent.com/2956728/52692831-5a72e080-2fa8-11e9-9d81-318b2dee6a08.jpg)
![19ju](https://user-images.githubusercontent.com/2956728/52692913-8e4e0600-2fa8-11e9-8508-26c90f7faccb.jpg)

![19full](https://user-images.githubusercontent.com/2956728/52693058-01577c80-2fa9-11e9-8143-0221281499ea.jpg)

**Comment by minsoo-jun** [comment]
for 18
![18logo](https://user-images.githubusercontent.com/2956728/52693997-b7bc6100-2fab-11e9-91b0-7a0091bb747f.jpg)

![18san](https://user-images.githubusercontent.com/2956728/52694057-dde20100-2fab-11e9-986c-590ce098df8b.jpg)
![18jun](https://user-images.githubusercontent.com/2956728/52694124-0e299f80-2fac-11e9-9396-7c001340a42c.jpg)

![18full](https://user-images.githubusercontent.com/2956728/52694251-62cd1a80-2fac-11e9-8fa9-f764ee53c2a6.jpg)

**Comment by minsoo-jun** [comment]
![freakout_new](https://user-images.githubusercontent.com/2956728/52695008-bc364900-2fae-11e9-9d2c-e7bfcf2e671a.png)

**Comment by minsoo-jun** [comment]
for 17
![17ike](https://user-images.githubusercontent.com/2956728/52696498-7da28d80-2fb2-11e9-8fe7-8130d418fc6e.jpg)

![17jon](https://user-images.githubusercontent.com/2956728/52696602-b9d5ee00-2fb2-11e9-8931-7f086cce659e.jpg)

![17lee](https://user-images.githubusercontent.com/2956728/52696680-ee49aa00-2fb2-11e9-94c9-0d3b1adad26c.jpg)

![17moon](https://user-images.githubusercontent.com/2956728/52696757-25b85680-2fb3-11e9-803c-a2c770b9c765.jpg)

![17full](https://user-images.githubusercontent.com/2956728/52696868-7c259500-2fb3-11e9-8873-8e7e01b9dee6.jpg)

![origami](https://user-images.githubusercontent.com/2956728/52696939-a6775280-2fb3-11e9-80bc-8d4c4e297913.png)

**Comment by minsoo-jun** [comment]
for 16
![16moon](https://user-images.githubusercontent.com/2956728/52698638-3e2a7000-2fb7-11e9-8540-7b2d1fb54098.jpg)

![16jun](https://user-images.githubusercontent.com/2956728/52698719-792ca380-2fb7-11e9-8ee6-39faa7b4d18c.jpg)

![16lee](https://user-images.githubusercontent.com/2956728/52698804-a1b49d80-2fb7-11e9-9abf-9bb3aa9cba0a.jpg)

![16june](https://user-images.githubusercontent.com/2956728/52698928-efc9a100-2fb7-11e9-922f-e83d786c8c72.jpg)

![16full](https://user-images.githubusercontent.com/2956728/52699185-85653080-2fb8-11e9-8197-bd8fb21332fb.jpg)

**Comment by minsoo-jun** [comment]
![referme_log](https://user-images.githubusercontent.com/2956728/52701245-20f8a000-2fbd-11e9-8e46-bfd7c3470da3.png)

**Comment by minsoo-jun** [comment]
for 15
![15sang](https://user-images.githubusercontent.com/2956728/52754673-bab46180-303e-11e9-82ee-83756adb1ad8.jpg)

![15iku](https://user-images.githubusercontent.com/2956728/52754744-fb13df80-303e-11e9-808d-ba88e4beb1d4.jpg)

![15park](https://user-images.githubusercontent.com/2956728/52754803-2991ba80-303f-11e9-9821-3a6f997e41ab.jpg)

![15ahn](https://user-images.githubusercontent.com/2956728/52754853-51811e00-303f-11e9-9b46-799dbffb836f.jpg)

![15full](https://user-images.githubusercontent.com/2956728/52755024-e2f09000-303f-11e9-9111-48e8361e1104.jpg)

![line](https://user-images.githubusercontent.com/2956728/52755120-277c2b80-3040-11e9-86eb-ef5d9535ce32.png)

**Comment by minsoo-jun** [comment]
for 14
![14doil](https://user-images.githubusercontent.com/2956728/52755475-6f4f8280-3041-11e9-9c5b-a63cbf7d2d99.jpg)

![14moon](https://user-images.githubusercontent.com/2956728/52755530-9dcd5d80-3041-11e9-961d-255314ce3a23.jpg)

![14dae](https://user-images.githubusercontent.com/2956728/52755634-edac2480-3041-11e9-8bf2-31d1b1d51f17.jpg)

![14full](https://user-images.githubusercontent.com/2956728/52755729-41b70900-3042-11e9-9fd9-5d80c10520df.jpg)

![rakuten](https://user-images.githubusercontent.com/2956728/52755772-657a4f00-3042-11e9-846d-e2e9e76e8b5a.png)

**Comment by minsoo-jun** [comment]
for 13
![13logo](https://user-images.githubusercontent.com/2956728/52765225-95d3e480-3066-11e9-81de-992effef156f.png)

**Comment by minsoo-jun** [comment]
for 12
![12oz](https://user-images.githubusercontent.com/2956728/52765749-5e663780-3068-11e9-92d3-b866217bed9f.jpg)

![12san](https://user-images.githubusercontent.com/2956728/52765828-9d948880-3068-11e9-8367-a7c0f3e963df.jpg)

![12san2](https://user-images.githubusercontent.com/2956728/52765906-dd5b7000-3068-11e9-8792-5b3312690c93.jpg)
![12fish](https://user-images.githubusercontent.com/2956728/52765965-0845c400-3069-11e9-98f4-725775b34509.jpg)

![12full](https://user-images.githubusercontent.com/2956728/52766045-4347f780-3069-11e9-9f58-afb3121320b3.jpg)

for 11
![11logo](https://user-images.githubusercontent.com/2956728/52766248-f284ce80-3069-11e9-8e76-d6ff749227db.png)

![11jun](https://user-images.githubusercontent.com/2956728/52766363-4d1e2a80-306a-11e9-82a1-9873d05b7197.jpg)
![12masa](https://user-images.githubusercontent.com/2956728/52766428-776fe800-306a-11e9-9fe6-daff9c131083.jpg)

![11fish](https://user-images.githubusercontent.com/2956728/52766480-a2f2d280-306a-11e9-91ba-effd68969e39.jpg)
![11full](https://user-images.githubusercontent.com/2956728/52766654-2dd3cd00-306b-11e9-9985-2b974808a3c8.jpg)

for 10
![10moon](https://user-images.githubusercontent.com/2956728/52766889-029dad80-306c-11e9-95fa-d7e1d3e12c5b.jpg)

![10eri](https://user-images.githubusercontent.com/2956728/52766951-3aa4f080-306c-11e9-88cc-cf3e9e24b700.jpg)

![10jeon](https://user-images.githubusercontent.com/2956728/52767017-7475f700-306c-11e9-8cbf-82cb86f56eb4.jpg)

![10full](https://user-images.githubusercontent.com/2956728/52767138-e0f0f600-306c-11e9-8005-14ec26587ca8.jpg)

![10logo](https://user-images.githubusercontent.com/2956728/52767183-067dff80-306d-11e9-88fb-a4b07d7481ab.png)

**Comment by minsoo-jun** [comment]
for 9
![09logo](https://user-images.githubusercontent.com/2956728/52768622-5a8ae300-3071-11e9-9e75-a7ef7c4897ab.jpg)

![09yasa](https://user-images.githubusercontent.com/2956728/52768873-07656000-3072-11e9-8f30-0e8b092e22c8.jpg)

![09jun](https://user-images.githubusercontent.com/2956728/52768926-354aa480-3072-11e9-9466-8028fd2c6c3c.jpg)

![09oz](https://user-images.githubusercontent.com/2956728/52769208-fa953c00-3072-11e9-9ff4-c3f4c0c2a44a.jpg)

![09full](https://user-images.githubusercontent.com/2956728/52769350-5d86d300-3073-11e9-8b16-d8382b746391.jpg)

for 08
![08logo](https://user-images.githubusercontent.com/2956728/52769836-d9cde600-3074-11e9-90de-e24d7d1f916c.jpg)

![08river](https://user-images.githubusercontent.com/2956728/52769951-37623280-3075-11e9-9f15-e0bc7be3101d.jpg)

![08laby](https://user-images.githubusercontent.com/2956728/52770115-9a53c980-3075-11e9-975a-8cf881ef35cb.jpg)

![08full](https://user-images.githubusercontent.com/2956728/52770244-e4d54600-3075-11e9-86ac-fb5331e7ea98.jpg)

**Comment by minsoo-jun** [comment]
for 07

![08yong](https://user-images.githubusercontent.com/2956728/52770632-f834e100-3076-11e9-9626-618d4ce97f99.jpg)

![07ka](https://user-images.githubusercontent.com/2956728/52770703-24e8f880-3077-11e9-99eb-42a9be8f800e.jpg)

![07kim](https://user-images.githubusercontent.com/2956728/52770767-519d1000-3077-11e9-8c29-9ba420eb16b8.jpg)

![07full](https://user-images.githubusercontent.com/2956728/52770849-932dbb00-3077-11e9-8df8-b8903d512613.jpg)

for 06
![06full](https://user-images.githubusercontent.com/2956728/52771072-40083800-3078-11e9-8ebb-dab7de52a274.jpg)
![06logo](https://user-images.githubusercontent.com/2956728/52771115-60d08d80-3078-11e9-8966-1c23e638c0ed.png)

for 05
![05logo](https://user-images.githubusercontent.com/2956728/52772896-01c14780-307d-11e9-81b0-b2911dd57b9d.png)
![051](https://user-images.githubusercontent.com/2956728/52773021-58c71c80-307d-11e9-94b1-b6899f463c7c.jpg)

![05ju](https://user-images.githubusercontent.com/2956728/52773105-844a0700-307d-11e9-821f-82a70d164c9d.jpg)

<img width="688" alt="screen shot 2019-02-14 at 17 28 06" src="https://user-images.githubusercontent.com/2956728/52773283-ee62ac00-307d-11e9-9ba7-e0a06c4d4c2d.png">

![05yoda](https://user-images.githubusercontent.com/2956728/52773392-2833b280-307e-11e9-87c1-f7657957ba5a.jpg)

![05mnsa](https://user-images.githubusercontent.com/2956728/52773476-5b764180-307e-11e9-9196-eed4a4451518.jpg)

![05full](https://user-images.githubusercontent.com/2956728/52773581-a98b4500-307e-11e9-8815-6d9f97fc88aa.jpg)

for 04
![04logo](https://user-images.githubusercontent.com/2956728/52773838-39c98a00-307f-11e9-86b0-2bae479a67d9.png)

![04full](https://user-images.githubusercontent.com/2956728/52773976-962ca980-307f-11e9-9c8c-5d5b9c44bb4c.jpg)

![04jun](https://user-images.githubusercontent.com/2956728/52774198-09362000-3080-11e9-906f-27559bfc6fda.jpg)

![04kim](https://user-images.githubusercontent.com/2956728/52774296-384c9180-3080-11e9-8b59-f5e601689013.jpg)

![04lee](https://user-images.githubusercontent.com/2956728/52774393-69c55d00-3080-11e9-9281-bc65af24b560.jpg)

![03full](https://user-images.githubusercontent.com/2956728/52774837-8ca44100-3081-11e9-9b6a-6a360799a8b9.jpg)

![03lee](https://user-images.githubusercontent.com/2956728/52775174-603cf480-3082-11e9-8195-c24750f0cc9f.jpg)

![03kim](https://user-images.githubusercontent.com/2956728/52775259-94181a00-3082-11e9-953a-f5704de8183c.jpg)

![03il](https://user-images.githubusercontent.com/2956728/52775326-c0339b00-3082-11e9-8739-f66a25c90271.jpg)

for 02
![02full](https://user-images.githubusercontent.com/2956728/52775645-7d25f780-3083-11e9-9f48-1e8ee8461523.jpg)

![02han](https://user-images.githubusercontent.com/2956728/52775795-d726bd00-3083-11e9-9363-a64db7741239.jpg)

![02ahn](https://user-images.githubusercontent.com/2956728/52775869-ffaeb700-3083-11e9-91c5-1a94a0a10fb9.jpg)
![02kim](https://user-images.githubusercontent.com/2956728/52775954-279e1a80-3084-11e9-84a8-7e2a5590ece8.jpg)

![02monn](https://user-images.githubusercontent.com/2956728/52776083-54523200-3084-11e9-8ac5-739be2029a15.jpg)

for 1
![01full](https://user-images.githubusercontent.com/2956728/52776467-ff62eb80-3084-11e9-8b7a-0016a952afde.jpg)

![01jun](https://user-images.githubusercontent.com/2956728/52776583-4650e100-3085-11e9-8f0d-309fb720b56a.jpg)

![01lee](https://user-images.githubusercontent.com/2956728/52776648-67b1cd00-3085-11e9-9795-392090a5056d.jpg)

![01oz](https://user-images.githubusercontent.com/2956728/52776706-84e69b80-3085-11e9-8658-c7c6c2edf9f4.jpg)
